### ISSUE TITLE
Synthesis fails with the error `ENAMETOOLONG`

### ISSUE THREAD

**Issue by otaviomacedo** [cdklabs/decdk#164]
### Describe the bug

For some templates, the synthesis fails with the error `ENAMETOOLONG`.

### Expected behavior

Synthesize the template successfully.

### Current behavior

Running `decdk` on some templates leads to the error:

```
Error: ENAMETOOLONG: name too long, mkdir '/Users/otaviom/projects/decdk/examples/cdk.out/asset.5205744804b6ed271bb4809a866fc56a2c53383a68ce2919e707afc0730cd523/cdk.out/asset.15689ac064b611030f942500c2748f742e64ae1901db7bec75f6fbcb5924f628/cdk.out/asset.15689ac064b611030f942500c2748f742e64ae1901db7bec75f6fbcb5924f628/cdk.out/asset.15689ac064b611030f942500c2748f742e64ae1901db7bec75f6fbcb5924f628/cdk.out/asset.15689ac064b611030f942500c2748f742e64ae1901db7bec75f6fbcb5924f628/cdk.out/asset.15689ac064b611030f942500c2748f742e64ae1901db7bec75f6fbcb5924f628/cdk.out/asset.15689ac064b611030f942500c2748f742e64ae1901db7bec75f6fbcb5924f628/cdk.out/asset.15689ac064b611030f942500c2748f742e64ae1901db7bec75f6fbcb5924f628/cdk.out/asset.15689ac064b611030f942500c2748f742e64ae1901db7bec75f6fbcb5924f628/cdk.out/asset.15689ac064b611030f942500c2748f742e64ae1901db7bec75f6fbcb5924f628/cdk.out/asset.15689ac064b611030f942500c2748f742e64ae1901db7bec75f6fbcb5924f628/cdk.out/asset.15689ac064b611030f942500c2748f742e64ae1901db7bec75f6fbcb5924f628/cdk.out/asset.15689ac064b611030f942500c2748f742e64ae1901db7bec75f6fbcb5924f628'
```

It seems it's producing a symlink that points to the directory that contains it.

### Reproduction steps

Run `cdk -a "decdk lambda-topic.json" synth` on the `examples` folder of this repo.

**Comment by mrgrain** [comment]
Currently failing with this error:
```
examples/apigw.json
examples/lambda-events.json
examples/lambda-role-removed.json
examples/lambda-topic.json
```

All are using `"fromAsset": { "path": "." }`

**Comment by mrgrain** [comment]
Reproduced with classic CDK. Error messages is basically the same an equally unusable.
```
new lambda.Function(this, "Function", {
  runtime: lambda.Runtime.NODEJS_16_X,
  handler: "lambda.handler",
  code: Code.fromAsset("."),
});
```
I don't think this is producing a symlink, but rather an issue with the recursive implementation of [copyDirectory](https://github.com/aws/aws-cdk/blob/9241f46949c0ab0a2d6fad8e0d6f2ff65a87a67e/packages/@aws-cdk/core/lib/fs/copy.ts#L47-L51) algorithm. The `.` path will include `cdk.out`, which we are also copying files to. So any file that is copied to the asset is immediately discovered as a new file that needs copying.

**Comment by mrgrain** [comment]
Related aws-cdk issue https://github.com/aws/aws-cdk/issues/3899
