### ISSUE TITLE
Block the use of user assets

### ISSUE THREAD

**Issue by otaviomacedo** [cdklabs/decdk#200]
In some environments (e.g., in a Lambda function), the application won't have access to any assets. So constructions like:

```json
"HelloLambda": {
  "Type": "aws-cdk-lib.aws_lambda.Function",
  "Properties": {
    "code": {
      "fromAsset": { "path": "." }
    }
    ...
  }
}
```

should fail with a user-friendly message. This behavior should be controlled by a command line option to deCDK.

**Comment by mrgrain** [comment]
Somewhere @rix0rrr suggested we use a custom synthesizer for `decdk`. Would that possibly solve the problem in a generic way? Arguably we might want synthesizer support anyway.
