### ISSUE TITLE
Integrations as their own resource types

### ISSUE THREAD

**Issue by otaviomacedo** [cdklabs/decdk#203]
Currently, integrations are configured by calling methods on the resources. For example:

```ts
bucket.addEventNotification(s3.EventType.OBJECT_CREATED, new s3n.SnsDestination(topic));
```

There will be support for generic function calls, but for this particular pattern, the UX would be better if we had integrations as their own resource types. Something like:

```json
"SnsDestination": {
  "Type": "aws-cdk-lib.aws_s3_notifications.SnsDestination", // Maybe a different name
  "Properties": {
    "bucket": {
      "Ref": "MyBucket"
    },
    "eventType": "OBJECT_CREATED",
    "topic": {
      "Ref": "MyTopic"
    }
  }
}
```

**Comment by mrgrain** [comment]
For this specific example, I think the right way would be to introduce an extended design to the underlying CDK module.
Spefically we could have a top-level classes/constucts `s3n.SnsNotification(props)` that wraps the above calls.

**Comment by otaviomacedo** [comment]
Out of scope for now. If we decide to bring this back, it will need some deeper discussion and design.
