### ISSUE TITLE
Parser does not support `Fn::GetAtt` dot notation shorthand

### ISSUE THREAD

**Issue by mrgrain** [cdklabs/decdk#211]
https://twitter.com/SeanTylerMyers/status/1525305955583307777
> CFN unique parsing find today: "Fn::GetAtt" has a shorthand in YAML that actually works in JSON as well, so `{"Fn::GetAtt": "IamRole.Arn"}` is valid.

**Comment by lejiati** [comment]
Hey Momo, 

Just trying to get some clarity, do we plan to support `{"Fn::GetAtt": "logicalNameOfResource.attributeName"}` even this is not documented in CFN docs, is this for compatibility purpose?

**Comment by mrgrain** [comment]
@lejiati Good question! I think we can make a decision on this. It's definitely a "nice to have" hence, the p2 label.

It came up in discussions between @rix0rrr @otaviomacedo and me, looking at what other CFN parsers (including the one in CDK) are already supporting. Issue was mainly intended as a reminder of this. I'll make sure to make this clearer next time.
