### ISSUE TITLE
Type system is loaded multiple times in tests

### ISSUE THREAD

**Issue by otaviomacedo** [cdklabs/decdk#382]
In Jest, [every single test file gets its own context][1]. The implication of that for deCDK tests is that the jsii type system is loaded multiple times. As we add more assemblies (e.g, for the alpha modules), the total running time becomes unworkable.

[1]: https://github.com/facebook/jest/issues/6007#issuecomment-381743011

**Comment by mrgrain** [comment]
Hmm. I thought that's why we cache it here 🤔 
https://github.com/cdklabs/decdk/blob/main/test/util.ts#L15-L21

Did you observe the caching not working as expected?

**Comment by otaviomacedo** [comment]
> Did you observe the caching not working as expected?

Yes. The cache works within the same test file. But each test file has its own context, so it starts from a clean slate. In particular, from `_cachedTS == undefined`.
