### ISSUE TITLE
Automated testing of L2s in deCDK

### ISSUE THREAD

**Issue by Chriscbr** [cdklabs/decdk#56]
An automated test that tries creating every L2 construct by simply initializing it with the minimum parameters.

deCDK is not coupled to a specific version of AWS CDK, and it doesn't make sense to test this for every possible version of AWS CDK, so we can probably just test this on the minimum and maximum versions of AWS CDK that are supported.

Investigate if we can re-use something from https://github.com/cdklabs/cdk-generate-synthetic-examples.

**Comment by rix0rrr** [comment]
Good idea, but unlikely we are going to do this. I'm going to close it out.
