### ISSUE TITLE
Option to output generated CDK code

### ISSUE THREAD

**Issue by Chriscbr** [cdklabs/decdk#80]
Currently deCDK performs the entire transformation from YAML, to runtime calls of the AWS CDK APIs, and then back to YAML.

Add an option to generate the AWS CDK code directly (stopping after the second step) in TypeScript or other languages.

One way to achieve this might be to add deCDK support into [cdk-dasm](https://www.npmjs.com/package/cdk-dasm).

Another way might be to rearchitect deCDK so that instead of invoking AWS CDK APIs during runtime, it instead does actual code generation, and then runs that code to generate the YAML.

**Comment by mrgrain** [comment]
This is out of scope for this project for now.
